apiVersion: v1
kind: Service
metadata:
  name: {{ include "jrpc-interceptor.fullname" . }}
  labels:
    {{- include "jrpc-interceptor.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.ports.http }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.ports.metrics }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "jrpc-interceptor.selectorLabels" . | nindent 4 }}
